#!/usr/bin/env bash
#
# generate-policy-report.sh — Produce a GitHub job summary from the
# PolicyMesh CI Checker's GitHub-formatted output.
#
# The CI checker supports "--output github" which emits GitHub-flavored
# Markdown (see ci-checker/src/main/java/com/policymesh/ci/output/GithubReporter.java).
# This script runs the checker, captures the Markdown, appends it to
# $GITHUB_STEP_SUMMARY, and also saves the JSON report as a build artifact.
#
# Usage:
#   .github/scripts/generate-policy-report.sh \
#     --services ./examples/services.json \
#     --dataflows ./examples/dataflows-valid.json
#
# Environment:
#   GITHUB_STEP_SUMMARY  set automatically by GitHub Actions
#   GITHUB_WORKSPACE     set automatically by GitHub Actions
#   SKIP_BUILD           set to "1" to reuse existing JAR (default: build)
#   REPORT_JSON_PATH     override path for JSON artifact (default: /tmp/compliance-report.json)
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

JAR_PATH="${REPO_ROOT}/ci-checker/target/policymesh-ci.jar"
REPORT_JSON_PATH="${REPORT_JSON_PATH:-/tmp/compliance-report.json}"
SUMMARY_FILE="${GITHUB_STEP_SUMMARY:-/tmp/github-step-summary.md}"

# ---------------------------------------------------------------------------
# Build the checker JAR (reuse if SKIP_BUILD=1)
# ---------------------------------------------------------------------------
if [ "${SKIP_BUILD:-0}" != "1" ]; then
    echo "Building CI checker..."
    (cd "${REPO_ROOT}/ci-checker" && mvn -q clean package -DskipTests)
fi

if [ ! -f "$JAR_PATH" ]; then
    echo "ERROR: JAR not found at ${JAR_PATH}"
    exit 1
fi

# ---------------------------------------------------------------------------
# Prepare clean policy directory (same logic as run-policy-check.sh)
# ---------------------------------------------------------------------------
TEMP_POLICY_DIR=$(mktemp -d)
trap 'rm -rf "$TEMP_POLICY_DIR"' EXIT

SOURCE_POLICY_DIR="${POLICY_DIR:-${REPO_ROOT}/policies}"

for region in EU GLOBAL INDIA US; do
    if [ -d "${SOURCE_POLICY_DIR}/${region}" ]; then
        cp -r "${SOURCE_POLICY_DIR}/${region}" "${TEMP_POLICY_DIR}/${region}"
    fi
done

echo "Total policy files: $(find "${TEMP_POLICY_DIR}" -name '*.yaml' -o -name '*.yml' | wc -l)"

# ---------------------------------------------------------------------------
# Run the checker in both github-markdown and json modes
# ---------------------------------------------------------------------------
echo ""
echo "=== Generating PolicyMesh Compliance Summary ==="

# Capture GitHub Markdown for the job summary
MARKDOWN_OUTPUT=$(java -jar "${JAR_PATH}" check \
    --policy-dir "${TEMP_POLICY_DIR}" \
    --output github \
    "$@" 2>/dev/null) || true

# Capture JSON for artifact upload
java -jar "${JAR_PATH}" check \
    --policy-dir "${TEMP_POLICY_DIR}" \
    --output json \
    "$@" > "${REPORT_JSON_PATH}" 2>/dev/null || true

# ---------------------------------------------------------------------------
# Write to GitHub Step Summary
# ---------------------------------------------------------------------------
{
    if [ -n "$MARKDOWN_OUTPUT" ]; then
        # The checker's GithubReporter already emits its own Markdown heading
        echo "$MARKDOWN_OUTPUT"
    else
        echo "⚠️ No report was generated by the CI checker."
        echo ""
        echo "This could indicate a configuration error. Check the job logs for details."
    fi
} >> "$SUMMARY_FILE"

echo ""
echo "GitHub summary written to: ${SUMMARY_FILE}"
echo "JSON report saved to:     ${REPORT_JSON_PATH}"
echo ""
echo "--- Summary preview ---"
cat "$SUMMARY_FILE"
