apiVersion: v1
kind: Secret
metadata:
  name: policymesh-secrets
  namespace: policymesh
type: Opaque
stringData:
  DB_USERNAME: CHANGE_ME
  DB_PASSWORD: CHANGE_ME
  JWT_SECRET: CHANGE_ME
  INTERNAL_API_KEY: CHANGE_ME
  AI_API_KEY: CHANGE_ME
